export const SET_STATE = 'SET_STATE'
export const CHANGED_NAME = 'CHANGED_NAME'
export const CHANGED_DESC = 'CHANGED_DESC'
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const EDIT_ITEM_HANDLER = 'EDIT_ITEM_HANDLER'
export const EDIT_ITEM = 'EDIT_ITEM'
export const CHANGE_ITEM_INDEX = 'CHANGE_ITEM_INDEX'
export const INDEX_DOWN = 'INDEX_DOWN'
export const INDEX_UP = 'INDEX_UP'
export const TOGGLE_INPUT_HANDLER = 'TOGGLE_INPUT_HANDLER'
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'
export const TOGGLE_MODAL='TOGGLE_MODAL'


export const EMAIL_CHANGE='EMAIL_CHANGE'
export const PASSWORD_CHANGE='PASSWORD_CHANGE'
export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT'
